In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import io

print("Librerias importadas correctamente")

# ==============================================================================================

Librerias importadas correctamente

In [24]:
# leer el csv
csv_fle = pd.read_csv('./2025-04.csv')

# Mostrar el tama√±o del df (filas y columnas)
print("Tama√±o del df:")
display(csv_fle.shape)

# Mostrar una previsualizacion de los datos
print("Previsualizacion del df:\n")
display(csv_fle.head(50))

Tama√±o del df:

(1727987, 9)

Previsualizacion del df:

,Genero_Usuario,Edad_Usuario,Bici,Ciclo_Estacion_Retiro,Fecha_Retiro,Hora_Retiro,Ciclo_EstacionArribo,Fecha_Arribo,Hora_Arribo
0,F,22.0,2586485,107-108,31/03/2025,23:34:46,181,01/04/2025,00:00:12
1,M,50.0,8152522,384,31/03/2025,23:43:51,387,01/04/2025,00:00:16
2,M,24.0,4219945,021,31/03/2025,23:42:36,548,01/04/2025,00:00:23
3,M,32.0,2286540,271-272,31/03/2025,23:57:16,450,01/04/2025,00:00:31
4,M,26.0,5017868,538,31/03/2025,23:46:23,012,01/04/2025,00:00:31
5,M,22.0,5918198,260,31/03/2025,23:41:43,299,01/04/2025,00:00:37
6,M,32.0,7051410,702,31/03/2025,23:50:15,702,01/04/2025,00:00:39
7,M,28.0,4163572,116,31/03/2025,23:47:24,055,01/04/2025,00:00:51
8,M,27.0,8924565,175,31/03/2025,23:55:13,167,01/04/2025,00:01:01
9,M,29.0,5694922,030,31/03/2025,23:52:18,144,01/04/2025,00:01:01
10,M,46.0,8725350,308,31/03/2025,23:38:56,604,01/04/2025,00:01:07
11,M,46.0,7180367,621,31/03/2025,23:54:37,613,01/04/2025,00:01:08
12,M,26.0,2464774,486,31/03/2025,23:56:46,494,01/04/2025,00:01:09
13,M,21.0,5391321,192-193,31/03/2025,23:40:48,119,01/04/2025,00:01:10
14,F,48.0,8735250,154,31/03/2025,23:48:34,335,01/04/2025,00:01:30
15,M,38.0,8937120,326,31/03/2025,23:54:03,322,01/04/2025,00:01:31
16,M,22.0,5469341,182,31/03/2025,23:53:23,172,01/04/2025,00:01:35
17,F,24.0,2848075,596,31/03/2025,23:55:34,601,01/04/2025,00:01:40
18,M,41.0,7610181,560,31/03/2025,23:59:30,568,01/04/2025,00:01:42
19,M,28.0,8870065,052,31/03/2025,23:44:17,107-108,01/04/2025,00:01:47
20,?,33.0,5891015,347,31/03/2025,23:54:26,365,01/04/2025,00:01:54
21,M,38.0,4691630,139,31/03/2025,23:36:17,507,01/04/2025,00:02:02
22,F,30.0,7043060,228,31/03/2025,23:39:18,029,01/04/2025,00:02:07
23,M,36.0,3715992,126,31/03/2025,21:54:33,477,01/04/2025,00:02:33
24,F,21.0,2738052,556,31/03/2025,23:40:13,591,01/04/2025,00:02:34
25,M,26.0,5984869,255,31/03/2025,23:32:45,553,01/04/2025,00:02:48
26,M,23.0,3298825,043,31/03/2025,23:52:31,571,01/04/2025,00:02:50
27,M,27.0,3922341,052,31/03/2025,22:58:29,477,01/04/2025,00:02:50
28,M,21.0,5498340,136,31/03/2025,23:19:13,554,01/04/2025,00:02:53
29,M,25.0,5180658,136,31/03/2025,23:17:31,554,01/04/2025,00:02:56
30,M,24.0,6021687,405,31/03/2025,23:52:29,621,01/04/2025,00:03:01
31,M,27.0,5390968,634,31/03/2025,23:56:19,624,01/04/2025,00:03:07
32,F,24.0,5167069,004,31/03/2025,23:50:39,068,01/04/2025,00:03:09
33,M,35.0,5216403,133,31/03/2025,23:51:41,571,01/04/2025,00:03:15
34,F,25.0,7056013,038,31/03/2025,23:51:34,075,01/04/2025,00:03:20
35,M,28.0,7111388,127,31/03/2025,23:46:16,186,01/04/2025,00:03:29
36,M,33.0,6512834,099,31/03/2025,23:51:57,271-272,01/04/2025,00:03:29
37,M,34.0,5740915,119,31/03/2025,23:56:53,134,01/04/2025,00:03:32
38,M,33.0,3602208,119,31/03/2025,23:56:09,134,01/04/2025,00:03:33
39,M,37.0,2128213,032,31/03/2025,22:58:45,032,01/04/2025,00:03:34
40,M,25.0,7682438,164,31/03/2025,23:53:35,139,01/04/2025,00:03:37
41,F,62.0,8253171,283,31/03/2025,23:52:31,355,01/04/2025,00:03:39
42,?,27.0,6846612,052,31/03/2025,22:53:55,477,01/04/2025,00:03:46
43,?,42.0,5297817,007,31/03/2025,23:44:02,346,01/04/2025,00:03:49
44,M,26.0,6929970,242,31/03/2025,23:53:52,211,01/04/2025,00:04:05
45,M,29.0,7826639,087,31/03/2025,23:51:52,569,01/04/2025,00:04:08
46,M,26.0,6982177,242,31/03/2025,23:50:46,490,01/04/2025,00:04:16
47,M,23.0,5367297,563,31/03/2025,23:59:28,560,01/04/2025,00:04:27
48,M,37.0,2166619,507,31/03/2025,23:34:10,243,01/04/2025,00:04:31
49,M,47.0,2294403,038,31/03/2025,23:53:50,254,01/04/2025,00:04:36

In [25]:
# Regresar valores √∫nicos
print(csv_fle["Genero_Usuario"].unique())

['F' 'M' '?' 'O' nan]

In [27]:
# Contamos cantidad de registros para cada genero
print(csv_fle["Genero_Usuario"].value_counts(dropna=False))

Genero_Usuario
M      1177624
F       484899
O        32835
?        32628
NaN          1
Name: count, dtype: int64

In [29]:
# Agregamos todos los valores diferentes de "M" y "F" a "O" (other)
csv_fle["Genero_Usuario"] = csv_fle["Genero_Usuario"].where(csv_fle["Genero_Usuario"].isin(["M", "F"]), "O")
print(csv_fle["Genero_Usuario"].value_counts())

Genero_Usuario
M    1177624
F     484899
O      65464
Name: count, dtype: int64

In [32]:
# AHora vamos a cambiar los valores de edades de elementos flotantes a enteros (no necesitamos flotantes porque son edades)
csv_fle["Edad_Usuario"] = csv_fle["Edad_Usuario"].astype("Int64")
display(csv_fle.head(20))

,Genero_Usuario,Edad_Usuario,Bici,Ciclo_Estacion_Retiro,Fecha_Retiro,Hora_Retiro,Ciclo_EstacionArribo,Fecha_Arribo,Hora_Arribo
0,F,22,2586485,107-108,31/03/2025,23:34:46,181,01/04/2025,00:00:12
1,M,50,8152522,384,31/03/2025,23:43:51,387,01/04/2025,00:00:16
2,M,24,4219945,021,31/03/2025,23:42:36,548,01/04/2025,00:00:23
3,M,32,2286540,271-272,31/03/2025,23:57:16,450,01/04/2025,00:00:31
4,M,26,5017868,538,31/03/2025,23:46:23,012,01/04/2025,00:00:31
5,M,22,5918198,260,31/03/2025,23:41:43,299,01/04/2025,00:00:37
6,M,32,7051410,702,31/03/2025,23:50:15,702,01/04/2025,00:00:39
7,M,28,4163572,116,31/03/2025,23:47:24,055,01/04/2025,00:00:51
8,M,27,8924565,175,31/03/2025,23:55:13,167,01/04/2025,00:01:01
9,M,29,5694922,030,31/03/2025,23:52:18,144,01/04/2025,00:01:01
10,M,46,8725350,308,31/03/2025,23:38:56,604,01/04/2025,00:01:07
11,M,46,7180367,621,31/03/2025,23:54:37,613,01/04/2025,00:01:08
12,M,26,2464774,486,31/03/2025,23:56:46,494,01/04/2025,00:01:09
13,M,21,5391321,192-193,31/03/2025,23:40:48,119,01/04/2025,00:01:10
14,F,48,8735250,154,31/03/2025,23:48:34,335,01/04/2025,00:01:30
15,M,38,8937120,326,31/03/2025,23:54:03,322,01/04/2025,00:01:31
16,M,22,5469341,182,31/03/2025,23:53:23,172,01/04/2025,00:01:35
17,F,24,2848075,596,31/03/2025,23:55:34,601,01/04/2025,00:01:40
18,M,41,7610181,560,31/03/2025,23:59:30,568,01/04/2025,00:01:42
19,M,28,8870065,052,31/03/2025,23:44:17,107-108,01/04/2025,00:01:47

In [ ]:
# Cambiar el nombre de la columna "Bici" a "Bici_UUID"
csv_fle.rename(columns={"Bici": "Bici_UUID"}, inplace=True)
display(csv_fle.head(20))

,Genero_Usuario,Edad_Usuario,Bici_UUID,Ciclo_Estacion_Retiro,Fecha_Retiro,Hora_Retiro,Ciclo_EstacionArribo,Fecha_Arribo,Hora_Arribo
0,F,22,2586485,107-108,31/03/2025,23:34:46,181,01/04/2025,00:00:12
1,M,50,8152522,384,31/03/2025,23:43:51,387,01/04/2025,00:00:16
2,M,24,4219945,021,31/03/2025,23:42:36,548,01/04/2025,00:00:23
3,M,32,2286540,271-272,31/03/2025,23:57:16,450,01/04/2025,00:00:31
4,M,26,5017868,538,31/03/2025,23:46:23,012,01/04/2025,00:00:31
5,M,22,5918198,260,31/03/2025,23:41:43,299,01/04/2025,00:00:37
6,M,32,7051410,702,31/03/2025,23:50:15,702,01/04/2025,00:00:39
7,M,28,4163572,116,31/03/2025,23:47:24,055,01/04/2025,00:00:51
8,M,27,8924565,175,31/03/2025,23:55:13,167,01/04/2025,00:01:01
9,M,29,5694922,030,31/03/2025,23:52:18,144,01/04/2025,00:01:01
10,M,46,8725350,308,31/03/2025,23:38:56,604,01/04/2025,00:01:07
11,M,46,7180367,621,31/03/2025,23:54:37,613,01/04/2025,00:01:08
12,M,26,2464774,486,31/03/2025,23:56:46,494,01/04/2025,00:01:09
13,M,21,5391321,192-193,31/03/2025,23:40:48,119,01/04/2025,00:01:10
14,F,48,8735250,154,31/03/2025,23:48:34,335,01/04/2025,00:01:30
15,M,38,8937120,326,31/03/2025,23:54:03,322,01/04/2025,00:01:31
16,M,22,5469341,182,31/03/2025,23:53:23,172,01/04/2025,00:01:35
17,F,24,2848075,596,31/03/2025,23:55:34,601,01/04/2025,00:01:40
18,M,41,7610181,560,31/03/2025,23:59:30,568,01/04/2025,00:01:42
19,M,28,8870065,052,31/03/2025,23:44:17,107-108,01/04/2025,00:01:47